### ISSUE TITLE
DBもdocker composeで用意する

### ISSUE THREAD

**Issue by yassi-github** [higuruchi/participant-app#29]
DBを別に用意するのは(sqlファイルが用意されていても)やはり面倒くさい．

docker compose で起動しているので，DBもコンテナで用意すれば便利そう．

また，永続化するため，DBコンテナがマウントして使う用のディレクトリを，新たにリポジトリに作成する．

**Comment by higuruchi** [comment]
```
--snip--
participant-app_1     | Start participant-app on 1323!2022/01/17 11:13:07 database connection error: dial tcp 172.22.2.71:3306: connect: connection refused
--snip--
```

`docker-compose up --build`コマンドを実行した際、上記のエラーが出力されてparticipant-appコンテナが終了する。
データベースとのコネクションが拒否されてる模様

**Comment by yassi-github** [comment]
こちらの環境(`docker ps -a`では何も表示されず，新たにリポジトリをcloneしたものを使用した)ではエラーは確認できない．

docker composeを一旦downさせてみるとどうだろうか．

**Comment by higuruchi** [comment]
再度`docker-compose up --build`をしたらできた
